pipeline { 
agent any 
stages { 
stage('Build') { 
steps { 
} 
} 
echo "Building branch ${env.BRANCH_NAME}" 
stage('Test') { 
steps { 
echo "Testing branch ${env.BRANCH_NAME}" 
} 
} 
} 
post { 
always { 
echo "Pipeline finished for ${env.BRANCH_NAME}" 
} 
} 
}
