pipeline {
  agent any

  stages {
   
   stage('clone project') {
      steps {
           git branch:'master' , url:'https://github.com/gbanishpatil518-cmyk/Amazon.git'
       }
   }

   stage('clean') {
      steps {
           dir('Amazon/Amazon-Web') {
           sh 'mvn clean'
           }
       }
   }

   stage('compile') {
      steps {
        dir('Amazon/Amazon-Web') {
           sh 'mvn compile'
        }
       }
   }

   stage('test') {
      steps {
        dir('Amazon/Amazon-Web') {
           sh 'mvn test'
        }
       }
   }

   stage('build') {
      steps {
        dir('Amazon/Amazon-Web') {
           sh 'mvn clean install'
        }
       }
   }
 }
}
